name: release
on:
  push:
    tags:
    - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build-ipfs-binaries:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux]
        arch: [amd64, arm64]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: "scripts/build ${{ matrix.os }} ${{ matrix.arch }}"

    - uses: actions/upload-artifact@v3
      with:
        name: bin
        path: bin/kubo*

  release:
    runs-on: ubuntu-latest
    needs: [build-ipfs-binaries]

    steps:
    - uses: actions/checkout@v3

    - uses: actions/download-artifact@v3
      with:
        name: bin
        path: ./bin

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        body: IPFS
        draft: false
        prerelease: false

    - name: Upload release files
      run: scripts/action_release_bin
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        UPLOAD_URL: ${{ steps.create_release.outputs.upload_url }}

    - uses: eregon/publish-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_id: ${{ steps.create_release.outputs.id }}
